/*

 ---------- Optimal lazy rebalancing calculator:
 Copyright 2011 Albert Mao

 This program is free software: you can redistribute it and/or modify it under the terms of the
 GNU General Public License as published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License along with this program. If
 not, see <http://www.gnu.org/licenses/>.


 ---------- JavaScript BigInteger, SchemeNumber library:
 Copyright (c) 2010,2011 John Tobey
 Copyright (c) 2009 Matthew Crumley

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
if(!Array.prototype.map)Array.prototype.map=function(d,f){var l=this.length>>>0;if(typeof d!=="function")throw new TypeError;for(var g=Array(l),k=0;k<l;k++)if(k in this)g[k]=d.call(f,this[k],k,this);return g};function BigInteger(d,f){if(!(this instanceof BigInteger)){if(d instanceof BigInteger)return d;else if(typeof d==="undefined")return BigInteger.ZERO;return BigInteger.parse(d)}for(d=d||[];d.length&&!d[d.length-1];)--d.length;this._d=d;this._s=d.length?f||1:0}BigInteger.base=1E7;
BigInteger.base_log10=7;BigInteger.ZERO=new BigInteger([],0);BigInteger.ONE=new BigInteger([1],1);BigInteger.M_ONE=new BigInteger(BigInteger.ONE._d,-1);BigInteger._0=BigInteger.ZERO;BigInteger._1=BigInteger.ONE;
BigInteger.small=[BigInteger.ZERO,BigInteger.ONE,new BigInteger([2],1),new BigInteger([3],1),new BigInteger([4],1),new BigInteger([5],1),new BigInteger([6],1),new BigInteger([7],1),new BigInteger([8],1),new BigInteger([9],1),new BigInteger([10],1),new BigInteger([11],1),new BigInteger([12],1),new BigInteger([13],1),new BigInteger([14],1),new BigInteger([15],1),new BigInteger([16],1),new BigInteger([17],1),new BigInteger([18],1),new BigInteger([19],1),new BigInteger([20],1),new BigInteger([21],1),
new BigInteger([22],1),new BigInteger([23],1),new BigInteger([24],1),new BigInteger([25],1),new BigInteger([26],1),new BigInteger([27],1),new BigInteger([28],1),new BigInteger([29],1),new BigInteger([30],1),new BigInteger([31],1),new BigInteger([32],1),new BigInteger([33],1),new BigInteger([34],1),new BigInteger([35],1),new BigInteger([36],1)];BigInteger.digits="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
BigInteger.prototype.toString=function(d){d=+d||10;if(d<2||d>36)throw Error("illegal radix "+d+".");if(this._s===0)return"0";if(d===10){d=this._s<0?"-":"";d+=this._d[this._d.length-1].toString();for(var f=this._d.length-2;f>=0;f--){for(var l=this._d[f].toString();l.length<BigInteger.base_log10;)l="0"+l;d+=l}return d}else{f=BigInteger.digits;d=BigInteger.small[d];l=this._s;for(var g=this.abs(),k=[],h;g._s!==0;){h=g.divRem(d);g=h[0];h=h[1];k.push(f[h.valueOf()])}return(l<0?"-":"")+k.reverse().join("")}};
BigInteger.radixRegex=[/^$/,/^$/,/^[01]*$/,/^[012]*$/,/^[0-3]*$/,/^[0-4]*$/,/^[0-5]*$/,/^[0-6]*$/,/^[0-7]*$/,/^[0-8]*$/,/^[0-9]*$/,/^[0-9aA]*$/,/^[0-9abAB]*$/,/^[0-9abcABC]*$/,/^[0-9a-dA-D]*$/,/^[0-9a-eA-E]*$/,/^[0-9a-fA-F]*$/,/^[0-9a-gA-G]*$/,/^[0-9a-hA-H]*$/,/^[0-9a-iA-I]*$/,/^[0-9a-jA-J]*$/,/^[0-9a-kA-K]*$/,/^[0-9a-lA-L]*$/,/^[0-9a-mA-M]*$/,/^[0-9a-nA-N]*$/,/^[0-9a-oA-O]*$/,/^[0-9a-pA-P]*$/,/^[0-9a-qA-Q]*$/,/^[0-9a-rA-R]*$/,/^[0-9a-sA-S]*$/,/^[0-9a-tA-T]*$/,/^[0-9a-uA-U]*$/,/^[0-9a-vA-V]*$/,/^[0-9a-wA-W]*$/,
/^[0-9a-xA-X]*$/,/^[0-9a-yA-Y]*$/,/^[0-9a-zA-Z]*$/];
BigInteger.parse=function(d,f){function l(r){r=r.replace(/\s*[*xX]\s*10\s*(\^|\*\*)\s*/,"e");return r.replace(/^([+\-])?(\d+)\.?(\d*)[eE]([+\-]?\d+)$/,function(o,z,y,K,E){E=+E;var N=E<0,C=y.length+E;o=(N?y:K).length;E=(E=Math.abs(E))>=o?E-o+N:0;o=Array(E+1).join("0");y+=K;return(z||"")+(N?y=o+y:y+=o).substr(0,C+=N?o.length:0)+(C<y.length?"."+y.substr(C):"")})}d=d.toString();if(typeof f==="undefined"||+f===10)d=l(d);var g=/^([+\-]?)(0[xXcCbB])?([0-9A-Za-z]*)(?:\.\d*)?$/.exec(d);if(g){var k=g[1]||"+",
h=g[2]||"";g=g[3]||"";if(typeof f==="undefined")f=h==="0x"||h==="0X"?16:h==="0c"||h==="0C"?8:h==="0b"||h==="0B"?2:10;else if(f<2||f>36)throw Error("Illegal radix "+f+".");f=+f;if(!BigInteger.radixRegex[f].test(g))throw Error("Bad digit for radix "+f);g=g.replace(/^0+/,"").split("");if(g.length===0)return BigInteger.ZERO;k=k==="-"?-1:1;if(f==10){for(h=[];g.length>=BigInteger.base_log10;)h.push(parseInt(g.splice(-BigInteger.base_log10).join(""),10));h.push(parseInt(g.join(""),10));return new BigInteger(h,
k)}if(f===BigInteger.base)return new BigInteger(g.map(Number).reverse(),k);h=BigInteger.ZERO;f=BigInteger.small[f];for(var j=BigInteger.small,m=0;m<g.length;m++)h=h.multiply(f).add(j[parseInt(g[m],36)]);return new BigInteger(h._d,k)}else throw Error("Invalid BigInteger format: "+d);};
BigInteger.prototype.add=function(d){if(this._s===0)return BigInteger(d);d=BigInteger(d);if(d._s===0)return this;if(this._s!==d._s){d=d.negate();return this.subtract(d)}var f=this._d;d=d._d;for(var l=f.length,g=d.length,k=Array(Math.max(l,g)+1),h=Math.min(l,g),j=0,m=0;m<h;m++){j=f[m]+d[m]+j;k[m]=j%BigInteger.base;j=j/BigInteger.base|0}if(g>l){f=d;l=g}for(m=h;j&&m<l;m++){j=f[m]+j;k[m]=j%BigInteger.base;j=j/BigInteger.base|0}if(j)k[m]=j;for(;m<l;m++)k[m]=f[m];return new BigInteger(k,this._s)};
BigInteger.prototype.negate=function(){return new BigInteger(this._d,-this._s)};BigInteger.prototype.abs=function(){return this._s<0?this.negate():this};
BigInteger.prototype.subtract=function(d){if(this._s===0)return BigInteger(d).negate();d=BigInteger(d);if(d._s===0)return this;if(this._s!==d._s){d=d.negate();return this.add(d)}var f=this,l;if(this._s<0){l=f;f=new BigInteger(d._d,1);d=new BigInteger(l._d,1)}var g=f.compareAbs(d);if(g===0)return BigInteger.ZERO;else if(g<0){l=d;d=f;f=l}f=f._d;d=d._d;l=f.length;var k=d.length,h=Array(l),j=0,m,r;for(m=0;m<k;m++){r=f[m]-j-d[m];if(r<0){r+=BigInteger.base;j=1}else j=0;h[m]=r}for(m=k;m<l;m++){r=f[m]-j;
if(r<0)r+=BigInteger.base;else{h[m++]=r;break}h[m]=r}for(;m<l;m++)h[m]=f[m];return new BigInteger(h,g)};
(function(){function d(l,g){for(var k=l._d,h=k.slice(),j=0;;){var m=(k[j]||0)+1;h[j]=m%BigInteger.base;if(m<=BigInteger.base-1)break;++j}return new BigInteger(h,g)}function f(l,g){for(var k=l._d,h=k.slice(),j=0;;){var m=(k[j]||0)-1;if(m<0)h[j]=m+BigInteger.base;else{h[j]=m;break}++j}return new BigInteger(h,g)}BigInteger.prototype.next=function(){switch(this._s){case 0:return BigInteger.ONE;case -1:return f(this,-1);default:return d(this,1)}};BigInteger.prototype.prev=function(){switch(this._s){case 0:return BigInteger.M_ONE;
case -1:return d(this,-1);default:return f(this,1)}}})();BigInteger.prototype.compareAbs=function(d){if(this===d)return 0;if(!(d instanceof BigInteger)){if(!isFinite(d))return isNaN(d)?d:-1;d=BigInteger(d)}if(this._s===0)return d._s!==0?-1:0;if(d._s===0)return 1;var f=this._d.length,l=d._d.length;if(f<l)return-1;else if(f>l)return 1;l=this._d;d=d._d;for(f-=1;f>=0;f--)if(l[f]!==d[f])return l[f]<d[f]?-1:1;return 0};
BigInteger.prototype.compare=function(d){if(this===d)return 0;d=BigInteger(d);if(this._s===0)return-d._s;return this._s===d._s?this.compareAbs(d)*this._s:this._s};BigInteger.prototype.isUnit=function(){return this===BigInteger.ONE||this===BigInteger.M_ONE||this._d.length===1&&this._d[0]===1};
BigInteger.prototype.multiply=function(d){if(this._s===0)return BigInteger.ZERO;d=BigInteger(d);if(d._s===0)return BigInteger.ZERO;if(this.isUnit()){if(this._s<0)return d.negate();return d}if(d.isUnit()){if(d._s<0)return this.negate();return this}if(this===d)return this.square();var f=this._d.length>=d._d.length,l=(f?this:d)._d;f=(f?d:this)._d;var g=l.length,k=f.length,h=g+k,j=Array(h),m;for(m=0;m<h;m++)j[m]=0;for(m=0;m<k;m++){h=0;for(var r=f[m],o=g+m,z,y=m;y<o;y++){z=j[y]+r*l[y-m]+h;h=z/BigInteger.base|
0;j[y]=z%BigInteger.base|0}if(h){z=j[y]+h;j[y]=z%BigInteger.base}}return new BigInteger(j,this._s*d._s)};
BigInteger.prototype.multiplySingleDigit=function(d){if(d===0||this._s===0)return BigInteger.ZERO;if(d===1)return this;var f;if(this._d.length===1){f=this._d[0]*d;if(f>=BigInteger.base)return new BigInteger([f%BigInteger.base|0,f/BigInteger.base|0],1);return new BigInteger([f],1)}if(d===2)return this.add(this);if(this.isUnit())return new BigInteger([d],1);var l=this._d,g=l.length;f=g+1;for(var k=Array(f),h=0;h<f;h++)k[h]=0;for(var j=h=0;j<g;j++){f=d*l[j]+h;h=f/BigInteger.base|0;k[j]=f%BigInteger.base|
0}if(h)k[j]=h%BigInteger.base;return new BigInteger(k,1)};
BigInteger.prototype.square=function(){if(this._s===0)return BigInteger.ZERO;if(this.isUnit())return BigInteger.ONE;var d=this._d,f=d.length,l=Array(f+f+1),g,k,h,j;for(j=0;j<f;j++){h=j*2;g=d[j]*d[j];k=g/BigInteger.base|0;l[h]=g%BigInteger.base;l[h+1]=k}for(j=0;j<f;j++){k=0;h=j*2+1;for(var m=j+1;m<f;m++,h++){g=d[m]*d[j]*2+l[h]+k;k=g/BigInteger.base|0;l[h]=g%BigInteger.base}h=f+j;g=k+l[h];k=g/BigInteger.base|0;l[h]=g%BigInteger.base;l[h+1]+=k}return new BigInteger(l,1)};
BigInteger.prototype.quotient=function(d){return this.divRem(d)[0]};BigInteger.prototype.divide=BigInteger.prototype.quotient;BigInteger.prototype.remainder=function(d){return this.divRem(d)[1]};
BigInteger.prototype.divRem=function(d){d=BigInteger(d);if(d._s===0)throw Error("Divide by zero");if(this._s===0)return[BigInteger.ZERO,BigInteger.ZERO];if(d._d.length===1)return this.divRemSmall(d._s*d._d[0]);switch(this.compareAbs(d)){case 0:return[this._s===d._s?BigInteger.ONE:BigInteger.M_ONE,BigInteger.ZERO];case -1:return[BigInteger.ZERO,this]}var f=this._s*d._s,l=d.abs(),g=this._d.slice(),k=[],h,j=new BigInteger([],1);for(j._s=1;g.length;){j._d.unshift(g.pop());j=new BigInteger(j._d,1);if(j.compareAbs(d)<
0)k.push(0);else{if(j._s===0)h=0;else{var m=j._d.length;h=l._d.length;m=j._d[m-1]*BigInteger.base+j._d[m-2];h=l._d[h-1]*BigInteger.base+l._d[h-2];if(j._d.length>l._d.length)m=(m+1)*BigInteger.base;h=Math.ceil(m/h)}do{m=l.multiplySingleDigit(h);if(m.compareAbs(j)<=0)break;h--}while(h);k.push(h);if(h){h=j.subtract(m);j._d=h._d.slice()}}}return[new BigInteger(k.reverse(),f),new BigInteger(j._d,this._s)]};
BigInteger.prototype.divRemSmall=function(d){d=+d;if(d===0)throw Error("Divide by zero");var f=this._s*(d<0?-1:1);d=Math.abs(d);if(d<1||d>=BigInteger.base)throw Error("Argument out of range");if(this._s===0)return[BigInteger.ZERO,BigInteger.ZERO];if(d===1||d===-1)return[f===1?this.abs():new BigInteger(this._d,f),BigInteger.ZERO];if(this._d.length===1){var l=new BigInteger([this._d[0]/d|0],1);d=new BigInteger([this._d[0]%d|0],1);if(f<0)l=l.negate();if(this._s<0)d=d.negate();return[l,d]}var g=this._d.slice();
l=Array(g.length);for(var k=0,h=0,j=0,m;g.length;){k=k*BigInteger.base+g[g.length-1];if(k<d){l[j++]=0;g.pop();h=BigInteger.base*h+k}else{m=k===0?0:k/d|0;h=k-d*m;if(l[j++]=m){g.pop();k=h}else g.pop()}}d=new BigInteger([h],1);if(this._s<0)d=d.negate();return[new BigInteger(l.reverse(),f),d]};BigInteger.prototype.isEven=function(){var d=this._d;return this._s===0||d.length===0||d[0]%2===0};BigInteger.prototype.isOdd=function(){return!this.isEven()};BigInteger.prototype.sign=function(){return this._s};
BigInteger.prototype.isPositive=function(){return this._s>0};BigInteger.prototype.isNegative=function(){return this._s<0};BigInteger.prototype.isZero=function(){return this._s===0};
BigInteger.prototype.exp10=function(d){d=+d;if(d===0)return this;if(Math.abs(d)>Number(BigInteger.MAX_EXP))throw Error("exponent too large in BigInteger.exp10");if(d>0){for(var f=new BigInteger(this._d.slice(),this._s);d>=BigInteger.base_log10;d-=BigInteger.base_log10)f._d.unshift(0);if(d==0)return f;f._s=1;f=f.multiplySingleDigit(Math.pow(10,d));return this._s<0?f.negate():f}else if(-d>=this._d.length*BigInteger.base_log10)return BigInteger.ZERO;else{f=new BigInteger(this._d.slice(),this._s);for(d=
-d;d>=BigInteger.base_log10;d-=BigInteger.base_log10)f._d.shift();return d==0?f:f.divRemSmall(Math.pow(10,d))[0]}};
BigInteger.prototype.pow=function(d){if(this.isUnit())return this._s>0?this:BigInteger(d).isOdd()?this:this.negate();d=BigInteger(d);if(d._s===0)return BigInteger.ONE;else if(d._s<0)if(this._s===0)throw Error("Divide by zero");else return BigInteger.ZERO;if(this._s===0)return BigInteger.ZERO;if(d.isUnit())return this;if(d.compareAbs(BigInteger.MAX_EXP)>0)throw Error("exponent too large in BigInteger.pow");for(var f=this,l=BigInteger.ONE,g=BigInteger.small[2];d.isPositive();){if(d.isOdd()){l=l.multiply(f);
if(d.isUnit())break}f=f.square();d=d.quotient(g)}return l};BigInteger.prototype.modPow=function(d,f){for(var l=BigInteger.ONE,g=this;d.isPositive();){if(d.isOdd())l=l.multiply(g).remainder(f);d=d.quotient(BigInteger.small[2]);if(d.isPositive())g=g.square().remainder(f)}return l};
BigInteger.prototype.log=function(){switch(this._s){case 0:return-Infinity;case -1:return NaN}var d=this._d.length;if(d*BigInteger.base_log10<30)return Math.log(this.valueOf());var f=Math.ceil(30/BigInteger.base_log10),l=this._d.slice(d-f);return Math.log((new BigInteger(l,1)).valueOf())+(d-f)*Math.log(BigInteger.base)};BigInteger.prototype.valueOf=function(){return parseInt(this.toString(),10)};BigInteger.prototype.toJSValue=function(){return parseInt(this.toString(),10)};BigInteger.MAX_EXP=BigInteger(2147483647);
(function(){function d(g){return function(k){return g.call(BigInteger(k))}}function f(g){return function(k,h){return g.call(BigInteger(k),BigInteger(h))}}function l(g){return function(k,h,j){return g.call(BigInteger(k),BigInteger(h),BigInteger(j))}}(function(){var g,k,h="toJSValue,isEven,isOdd,sign,isZero,isNegative,abs,isUnit,square,negate,isPositive,toString,next,prev,log".split(","),j="compare,remainder,divRem,subtract,add,quotient,divide,multiply,pow,compareAbs".split(","),m=["modPow"];for(g=
0;g<h.length;g++){k=h[g];BigInteger[k]=d(BigInteger.prototype[k])}for(g=0;g<j.length;g++){k=j[g];BigInteger[k]=f(BigInteger.prototype[k])}for(g=0;g<m.length;g++){k=m[g];BigInteger[k]=l(BigInteger.prototype[k])}BigInteger.exp10=function(r,o){return BigInteger(r).exp10(o)}})()})();if(typeof exports!=="undefined")exports.BigInteger=BigInteger;BigInteger=typeof require!=="undefined"?require("biginteger").BigInteger:this.BigInteger;
if(!BigInteger)if(typeof load!=="undefined")load("biginteger.js");else if(this.readFile)eval(this.readFile("biginteger.js"));else throw Error("BigInteger is not defined.");
var SchemeNumber=function(){function d(){return false}function f(){return true}function l(a){return a}function g(){return this}function k(){return t}function h(){return s}function j(){L("&assertion","division by exact zero")}function m(){throw Error("BUG: unimplemented");}function r(){throw Error("BUG: Abstract method not overridden");}function o(a){if(a instanceof Number||typeof a==="number")return a;a=String(a);var c=y(a,void 0,void 0);c===false&&L("&assertion","not a number",a);return c}function z(a){return a instanceof
Number||typeof a==="number"}function y(a,c,e){function i(){throw Qa;}function n(p){c&&i();c=p}function q(p,v){za[c].test(p)||i();var u=parseInt(p,c);if(e===false)return A(v*u);if(u<9007199254740992)return F(v*u);u=BigInteger.parse(p,c);if(v<0)u=u.negate();return new J(u)}function w(p){if(mb.test(p)){e&&i();switch(p){case "+inf.0":return nb;case "-inf.0":return ob;default:return Ra}}var v=1;switch(p[0]){case "-":v=-1;case "+":p=p.substring(1)}var u=p.indexOf("/");if(u!=-1)return q(p.substring(0,u),
v).SN_divide(q(p.substring(u+1),1));c!==10&&i();u=p.indexOf("|");if(u!==-1){var I=p.substring(u+1);za[10].test(I)||i();p=p.substring(0,u);u=parseInt(I);if(u===0)p="0.0";else if(u<53){p=y(p,c,true);if(p===false||!p.SN_isReal())i();if(!p.SN_isZero()){I=p.SN_abs();var V=u-R(I.SN_log()/pb)-1;v=sa(M,Sa(V));if(V<0)v=v.SN_reciprocal();I=I.SN_multiply(v);for(u=sa(M,u);I.SN_ge(u);){I=I.SN_divide(M);v=v.SN_divide(M)}for(V=I.SN_add(I);V.SN_lt(u);V=I.SN_add(I)){I=V;v=v.SN_add(v)}v=I.SN_round().SN_divide(v);if(p.SN_isNegative())v=
v.SN_negate();p=v}e||(p=p.SN_toInexact());return p}}p=p.replace(qb,"e");var S=p.indexOf(".");u=p.indexOf("e");if(S===-1&&u===-1)return q(p,v);rb.test(p)||i();if(!e)return A(v*parseFloat(p));I=p.substring(0,S===-1?u:S);V=0;if(u===-1)S=p.substring(S+1);else{S=S===-1?"":p.substring(S+1,u);V=parseInt(p.substring(u+1))}return q(I+S,v).SN__exp10(V-S.length)}function B(p){var v=p.indexOf("@");if(v!==-1)return E(w(p.substring(0,v)),w(p.substring(v+1)));if(p[p.length-1]!=="i")return w(p);if(p==="i"){if(e===
false)return O(T,A(1));return W}if(p==="-i"){if(e===false)return O(T,A(-1));return Aa}var u=(c===10?sb:tb).exec(p);if(u){v=u[1];p=u[2];v=v?w(v):e===false?T:t;p=p==="+"?s:p==="-"?G:w(p)}else{v=e===false?T:t;p=w(p.substring(0,p.length-1))}return K(v,p)}var $=0;c=c||10;try{for(;a[$]==="#";){switch(a[$+1]){case "i":case "I":e!==undefined&&i();e=false;break;case "e":case "E":e!==undefined&&i();e=true;break;case "b":case "B":n(2);break;case "o":case "O":n(8);break;case "d":case "D":n(10);break;case "x":case "X":n(16);
break;default:return false}$+=2}return B(a.substring($))}catch(fa){if(fa===Qa)return false;a==undefined&&L("&assertion","missing argument");throw fa;}}function K(a,c){if(a.SN_isExact()&&c.SN_isExact())return ma(a,c);return O(a.SN_toInexact(),c.SN_toInexact())}function E(a,c){return O(a.SN_multiply(c.SN_cos()),a.SN_multiply(c.SN_sin()))}function N(a){a.SN_isReal()||L("&assertion","not a real number",a);return a}function C(a){a=o(a);a.SN_isReal()||N(a);return a}function Q(a){a=o(a);if(!a.SN_isInteger()){var c;
c=o(a);c.SN_isInteger()||L("&assertion","not an integer",c)}return a}function aa(a){a.SN_isRational()||L("&assertion","not a rational number",a);return a}function Ta(a){a.SN_isNegative()&&L("&assertion","negative number",a);return a}function Ua(a){a.SN_isInexact()&&L("&assertion","inexact number",a);return a}function Va(a,c,e){var i="SchemeNumber: "+a+": "+c;if(arguments.length>2){if(z(e))e=e.SN_numberToString();i+=": "+e}throw Error(i);}function L(){for(var a=arguments.length,c=Array(a);a--;)c[a]=
arguments[a];o.raise.apply(o,c);Va.apply(this,c)}function X(a,c){var e="Function";for(name in Wa)if(Wa[name]===c.callee){e+=" '"+name+"'";break}L("&assertion",e+" expected "+a+" argument"+(a=="1"?"":"s")+", got "+c.length)}function Y(a){a.length===1||X(1,a)}function ga(a){a.length===2||X(2,a)}function Ba(a){a.length>0||X("1 or more",a)}function Ca(a){arguments.length===1||Y(arguments);return z(a)&&a.SN_imagPart().SN_isZero()}function x(a){return function(c){arguments.length===1||Y(arguments);return o(c)[a]()}}
function ta(a){return function(c,e){var i=arguments.length;i>1||arguments.length>1||X("2 or more",arguments);e=C(e);if(!C(c)[a](e))return false;for(var n=2;n<i;n++){var q=C(arguments[n]);if(!e[a](q))return false;e=q}return true}}function Xa(a){return function(c){var e=arguments.length;e>0||Ba(arguments);for(var i=C(c),n=i.SN_isExact(),q=1;q<e;q++){var w=C(arguments[q]);if(w.SN_isNaN())return w;if(n)(n=w.SN_isExact())||(i=i.SN_toInexact());if(w[a](i)!==false)i=w}return n?i:i.SN_toInexact()}}function Ya(a){L("&assertion",
"div/mod second argument is zero",a)}function ha(a,c){return function(e,i){arguments.length===2||ga(arguments);e=C(e);i=C(i);e.SN_isFinite()||L("&assertion","div/mod first argument is not finite",e);i.SN_isZero()&&Ya(i);if(!a)switch(c){case 0:return e.SN_div(i);case 1:return e.SN_mod(i);default:return e.SN_divAndMod(i)}var n=e.SN_divAndMod(i),q=n[1],w=i.SN_abs();if(q.SN_add(q).SN_ge(w))switch(c){case 0:return n[0].SN_add(i.SN_isNegative()?G:s);case 1:return q.SN_subtract(w);default:return[n[0].SN_add(i.SN_isNegative()?
G:s),q.SN_subtract(w)]}switch(c){case 0:return n[0];case 1:return q;default:return n}}}function Za(a){a=Sa(a).toString(2);var c=a.indexOf(".");if(c===-1)return 0;return a.length-c-1}function Da(a){return na(2,Za(a))}function Ea(a){if(a<9007199254740992&&a>-9007199254740992)return F(a);return new J(BigInteger.parse(a.toString(16),16))}function Fa(a,c){if(c>0)return R(a/c);if(c<0)return ua(a/c);c==0&&Ya(A(c));return NaN}function va(){}function Ga(a){return K(a.SN_magnitude().SN_log(),a.SN_angle())}
function Ha(a){return Aa.SN_multiply(W.SN_multiply(a).SN_add(s.SN_subtract(a.SN_square()).SN_sqrt()).SN_log())}function $a(a){return Ia.SN_divide(M).SN_subtract(Ha(a))}function Ja(){}function oa(a,c){if(a.SN_isZero()){if(c.SN_isZero())return A(1);if(c.SN_realPart().SN_isPositive())return T;L("&implementation-restriction","invalid power for zero expt",c)}return a.SN_log().SN_multiply(c).SN_exp()}function ab(a,c){var e=pa(a,c);return[e,a.SN_subtract(e.SN_multiply(c))]}function pa(a,c){return c.SN_isNegative()?
a.SN_divide(c).SN_ceiling():a.SN_divide(c).SN_floor()}function ma(a,c){if(c.SN_isZero())return a;if(a.SN_isZero()&&c.SN_isUnit())return c.SN_isPositive()?W:Aa;return new ba(a,c)}function O(a,c){return new ba(a,c)}function ca(a,c){if(a.SN_isExact())return ma(a,c);return new ba(a,c)}function ba(a,c){this._x=a;this._y=c}function qa(a,c){if(c[0]==="-"||c[0]==="+")return a+c+"i";return a+"+"+c+"i"}function ra(a){return a._x.SN_square().SN_add(a._y.SN_square())}function bb(a,c,e,i){return ca(a.SN_multiply(e).SN_subtract(c.SN_multiply(i)),
a.SN_multiply(i).SN_add(c.SN_multiply(e)))}function cb(a,c,e){var i=ra(e);return bb(a,c,e._x.SN_divide(i),e._y.SN_divide(i).SN_negate())}function Ka(){}function ia(a){var c="000000000000000".substring(0,a&15);if(a>15)c+=Array((a>>4)+1).join("0000000000000000");return c}function wa(){}function U(a,c){c.SN_isZero()&&j();var e=La(a.SN_abs(),c.SN_abs());a=a.SN_div(e);c=c.SN_div(e);if(c.SN_isNegative())return P(a.SN_negate(),c.SN_negate());return P(a,c)}function P(a,c){return c===s?a:new ja(a,c)}function ja(a,
c){this._n=a;this._d=c}function xa(){}function sa(a,c){var e=na(a,c);if(e>-9007199254740992&&e<9007199254740992)return F(e);e=a.SN_log()*c;e>o.maxIntegerDigits*ya&&L("&implementation-restriction","exact integer would exceed limit of "+ +o.maxIntegerDigits+" digits; adjust SchemeNumber.maxIntegerDigits",e/ya);return new J(a.SN__toBigInteger().pow(c))}function db(a,c){for(var e=c.SN_abs(),i=a,n=s;e.SN_isPositive();){if(e.SN_isOdd())n=n.SN_multiply(i);i=i.SN_square();e=e.SN_div(M)}return c.SN_isNegative()?
n.SN_reciprocal():n}function Z(a){this._=a}function F(a){return ub[a]||(a==-1?G:new Z(a))}function eb(a){return a.SN_negate()}function vb(a){return a.SN_reciprocal()}function fb(a,c){var e=a+c;if(e>-9007199254740992&&e<9007199254740992)return F(e);return new J(BigInteger.add(a,c))}function Ma(a,c,e){c===0&&j();var i=c>0?R(a/c):ua(a/c);if(e===0)return F(i);var n=c*i;a=F(n>-9007199254740992?a-n:i>0?a-c-c*(i-1):a+c-c*(i+1));if(e===1)return a;return[F(i),a]}function ka(a){if(a.compareAbs(gb)>=0)return new J(a);
return F(a.toJSValue())}function J(a){this._=a}function hb(a,c){for(var e;a!==0;){e=a;a=c%a;c=e}return F(c)}function La(a,c){if(a instanceof Z&&c instanceof Z)return hb(a.valueOf(),c.valueOf());a=a.SN__toBigInteger();if(a.isZero())return c;c=c.SN__toBigInteger();for(var e;;){e=a;a=c.remainder(a);if(a.isZero())return new J(e);c=e;if(c.compareAbs(gb)<0)return hb(a.valueOf(),c.valueOf())}}function wb(a){function c($,fa,p){function v(u){if(!e[fa+u]){i[fa+u]=p;c(ib[u],fa,p)}}$&&$.forEach(v)}var e=b[a],
i={},n;for(n in e)if(/^SN_/.test(n)){a=n.lastIndexOf("_");if(a!==-1){var q=e[n];if(q){var w=n.substring(a+1);c(ib[w],n.substring(0,a+1),q)}}}for(var B in i)e[B]=i[B]}var Sa=Math.abs,R=Math.floor,ua=Math.ceil,xb=Math.round,na=Math.pow,Na=Math.sqrt,jb=Math.atan2,yb=Math.log,Oa=Math.exp,pb=Math.LN2,ya=Math.LN10,da=this.isFinite,la=this.isNaN,Pa=o;Pa.VERSION=[1,0,6];var A=Number,kb=na,lb=Number,ib={C:["Rectangular","R"],R:["Flonum","ER"],ER:["EQ"],EQ:["EQFraction","EI"],EI:["EINative","EIBig"]},ea={C:va,
R:Ja,ER:Ka,EQ:wa,EI:xa,Rectangular:ba,Flonum:lb,EQFraction:ja,EINative:Z,EIBig:J},b={},D;for(D in ea)b[D]={};var sb=/^(.*[^a-zA-Z]|)([-+].*)i$/,tb=/^(.*)([-+].*)i$/,mb=/^[-+](nan|inf)\.0$/,qb=/[eEsSfFdDlL]/,rb=/^([0-9]+\.?|[0-9]*\.[0-9]+)([eEsSfFdDlL][-+]?[0-9]+)?$/,za={2:/^[01]+$/,8:/^[0-7]+$/,10:/^[0-9]+$/,16:/^[0-9a-fA-F]+$/},Qa={};Pa.raise=Va;o.maxIntegerDigits=1E6;var Wa=Pa.fn={"eqv?":function(a,c){arguments.length===2||ga(arguments);if(a===c)return true;a=o(a);c=o(c);return a.SN_eq(c)&&a.SN_isExact()===
c.SN_isExact()},"number?":function(a){arguments.length===1||Y(arguments);return z(a)},"complex?":function(a){arguments.length===1||Y(arguments);return z(a)&&a.SN_isComplex()},"real?":function(a){arguments.length===1||Y(arguments);return z(a)&&a.SN_isReal()},"rational?":function(a){arguments.length===1||Y(arguments);return z(a)&&a.SN_isRational()},"integer?":function(a){arguments.length===1||Y(arguments);return z(a)&&a.SN_isInteger()},"real-valued?":Ca,"rational-valued?":function(a){arguments.length===
1||Y(arguments);return Ca(a)&&a.SN_realPart().SN_isRational()},"integer-valued?":function(a){arguments.length===1||Y(arguments);return Ca(a)&&a.SN_realPart().SN_isInteger()},"exact?":x("SN_isExact"),"inexact?":x("SN_isInexact"),inexact:x("SN_toInexact"),exact:x("SN_toExact"),"=":function(a){var c=arguments.length;c>1||arguments.length>1||X("2 or more",arguments);a=o(a);for(var e=1;e<c;e++)if(!a.SN_eq(o(arguments[e])))return false;return true},"<":ta("SN_lt"),">":ta("SN_gt"),"<=":ta("SN_le"),">=":ta("SN_ge"),
"zero?":x("SN_isZero"),"positive?":x("SN_isPositive"),"negative?":x("SN_isNegative"),"odd?":x("SN_isOdd"),"even?":x("SN_isEven"),"finite?":x("SN_isFinite"),"infinite?":x("SN_isInfinite"),"nan?":x("SN_isNaN"),max:Xa("SN_gt"),min:Xa("SN_lt"),"+":function(){for(var a=t,c=arguments.length,e=0;e<c;)a=a.SN_add(o(arguments[e++]));return a},"*":function(){for(var a=s,c=arguments.length,e=0;e<c;)a=a.SN_multiply(o(arguments[e++]));return a},"-":function(a){var c=arguments.length;switch(c){case 0:Ba(arguments);
case 1:return o(a).SN_negate()}for(var e=o(a),i=1;i<c;)e=e.SN_subtract(o(arguments[i++]));return e},"/":function(a){var c=arguments.length;switch(c){case 0:Ba(arguments);case 1:return o(a).SN_reciprocal();case 2:return o(a).SN_divide(o(arguments[1]))}for(var e=s,i=1;i<c;)e=e.SN_multiply(o(arguments[i++]));return o(a).SN_divide(e)},abs:x("SN_abs"),"div-and-mod":ha(false,2),div:ha(false,0),mod:ha(false,1),"div0-and-mod0":ha(true,2),div0:ha(true,0),mod0:ha(true,1),gcd:function(){for(var a=t,c=arguments.length,
e=true,i=0;i<c;i++){var n=Q(arguments[i]);e=e&&n.SN_isExact();a=La(a,n.SN_abs().SN_toExact())}a=a.SN_abs();return e?a:a.SN_toInexact()},lcm:function(){for(var a=s,c=arguments.length,e=true,i=0;i<c;i++){var n=Q(arguments[i]);e=e&&n.SN_isExact();n=n.SN_abs().SN_toExact();a=a.SN_multiply(n).SN_divide(La(a,n.SN_abs()))}return e?a:a.SN_toInexact()},numerator:x("SN_numerator"),denominator:x("SN_denominator"),floor:x("SN_floor"),ceiling:x("SN_ceiling"),truncate:x("SN_truncate"),round:x("SN_round"),rationalize:function(a,
c){ga(arguments);a=o(a);c=o(c);if(!a.SN_isFinite()||!c.SN_isFinite()){C(a);C(c);if(c.SN_isInfinite())return a.SN_isFinite()?T:Ra;if(c.SN_isNaN())return c;return a}if(c.SN_isZero())return a;c=c.SN_abs();var e=a.SN_subtract(c),i=a.SN_add(c),n=e.SN_floor(),q=i.SN_floor();if(n.SN_ne(q)){var w=n.SN_isNegative();if(q.SN_isNegative()!=w)return n.SN_isExact()?t:T;return w?q:e.SN_ceiling()}for(w=[];;){e=e.SN_subtract(n);if(e.SN_isZero())break;i=i.SN_subtract(n);if(i.SN_isZero())break;e=e.SN_reciprocal();i=
i.SN_reciprocal();n=e.SN_floor();switch(n.SN_compare(i.SN_floor())){case -1:w.push(e.SN_ceiling());break;case 1:w.push(i.SN_ceiling());break;default:w.push(n);continue}break}e=t;for(n=w.length;n--;)e=e.SN_add(w[n]).SN_reciprocal();return e.SN_add(q)},exp:x("SN_exp"),log:function(a,c){var e=o(a).SN_log();switch(arguments.length){case 2:e=e.SN_divide(o(c).SN_log());case 1:return e;default:X("1-2",arguments)}},sin:x("SN_sin"),cos:x("SN_cos"),tan:x("SN_tan"),asin:x("SN_asin"),acos:x("SN_acos"),atan:function(a,
c){switch(arguments.length){case 1:return o(a).SN_atan();case 2:return o(a).SN_atan2(c);default:X("1-2",arguments)}},sqrt:x("SN_sqrt"),"exact-integer-sqrt":x("SN_exactIntegerSqrt"),expt:function(a){return function(c,e){arguments.length===2||ga(arguments);return o(c)[a](o(e))}}("SN_expt"),"make-rectangular":function(a,c){arguments.length===2||ga(arguments);return K(C(a),C(c))},"make-polar":function(a,c){arguments.length===2||ga(arguments);return E(C(a),C(c))},"real-part":x("SN_realPart"),"imag-part":x("SN_imagPart"),
magnitude:x("SN_magnitude"),angle:x("SN_angle"),"number->string":function(a,c,e){var i=c;switch(arguments.length){case 3:e=Q(e);Ua(e);case 2:i=Ua(Q(i)).valueOf();za[i]||L("&assertion","invalid radix",c);case 1:break;default:X("1-3",arguments)}return o(a).SN_numberToString(i,e)},"string->number":function(a,c){switch(arguments.length){case 1:case 2:return y(String(a),c);default:X("1-2",arguments)}}};b.Flonum.SN_isExact=d;b.Flonum.SN_isInexact=f;b.Flonum.SN_isComplex=f;b.Flonum.SN_isReal=f;b.Flonum.SN_debug=
function(){return"Flonum("+this.SN_numberToString()+")"};b.Flonum.SN_numberToString=function(a,c){if(a&&a!=10&&da(this))return"#i"+this.SN_toExact().SN_numberToString(a);if(!da(this)){if(la(this))return"+nan.0";return this>0?"+inf.0":"-inf.0"}var e=this.toString();if(e.indexOf(".")===-1){var i=e.indexOf("e");if(i===-1)e+=".";else e=e.substring(0,i)+"."+e.substring(i)}if(c!=undefined){if(c<53){i=this.toString(2).replace(/[-+.]/g,"").replace(/^0+/,"").replace(/0+$/,"").length;if(c<i)c=i}e+="|"+c}return e};
b.Flonum.SN_realPart=g;b.Flonum.SN_imagPart=function(){return t};b.Flonum.SN_denominator=function(){return Da(aa(this))};b.Flonum.SN_numerator=function(){return this*Da(aa(this))};b.Flonum.SN_isInteger=function(){return da(this)&&this==R(this)};b.Flonum.SN_isFinite=function(){return da(this)};b.Flonum.SN_isRational=b.Flonum.SN_isFinite;b.Flonum.SN_isZero=function(){return this==0};b.Flonum.SN_isPositive=function(){return this>0};b.Flonum.SN_isNegative=function(){return this<0};b.Flonum.SN_sign=function(){return this==
0?0:this>0?1:-1};b.Flonum.SN_isUnit=function(){return this==1||this==-1};b.Flonum.SN_isInfinite=function(){return!da(this)&&!la(this)};b.Flonum.SN_isNaN=function(){return la(this)};b.Flonum.SN_isEven=function(){return(this&1)===0};b.Flonum.SN_isOdd=function(){return(this&1)===1};b.Flonum.SN_eq=function(a){return a.SN__eq_Flonum(this)};b.Flonum.SN_ne=function(a){return a.SN__ne_Flonum(this)};b.Flonum.SN_gt=function(a){return N(a).SN__gt_Flonum(this)};b.Flonum.SN_lt=function(a){return N(a).SN__lt_Flonum(this)};
b.Flonum.SN_ge=function(a){return N(a).SN__ge_Flonum(this)};b.Flonum.SN_le=function(a){return N(a).SN__le_Flonum(this)};b.Flonum.SN_compare=function(a){return N(a).SN__compare_Flonum(this)};b.Flonum.SN__eq_R=function(a){return+a==this};b.Flonum.SN__ne_R=function(a){return+a!=this};b.Flonum.SN__gt_R=function(a){return a>this};b.Flonum.SN__lt_R=function(a){return a<this};b.Flonum.SN__ge_R=function(a){return a>=this};b.Flonum.SN__le_R=function(a){return a<=this};b.Flonum.SN__compare_R=function(a){if(+a==
this)return 0;if(a<this)return-1;if(a>this)return 1;return NaN};b.Flonum.SN_toExact=function(){var a;a=+this;da(a)||L("&implementation-violation","inexact argument has no reasonably close exact equivalent",a);var c=Da(a);if(c===1)a=Ea(a);else{if(da(c)){a*=c;c=Ea(c)}else{c=Za(a);a*=9007199254740992;a*=na(2,c-53);c=sa(M,c)}a=P(Ea(a),c)}return a};b.Flonum.SN_toInexact=g;b.Flonum.SN_add=function(a){return a.SN__add_Flonum(this)};b.Flonum.SN_subtract=function(a){return a.SN__subtract_Flonum(this)};b.Flonum.SN_multiply=
function(a){return a.SN__multiply_Flonum(this)};b.Flonum.SN_divide=function(a){return a.SN__divide_Flonum(this)};b.Flonum.SN__add_R=function(a){return a+this};b.Flonum.SN__subtract_R=function(a){return a-this};b.Flonum.SN__multiply_R=function(a){return a*this};b.Flonum.SN__divide_R=function(a){return a/this};b.Flonum.SN_negate=function(){return-this};b.Flonum.SN_abs=function(){return this<0?-this:this};b.Flonum.SN_reciprocal=function(){return 1/this};b.Flonum.SN_divAndMod=function(a){a=+a;var c=Fa(this,
a);return[A(c),A(this-a*c)]};b.Flonum.SN_div=function(a){return Fa(this,a)};b.Flonum.SN_mod=function(a){return this-a*Fa(this,a)};b.Flonum.SN_square=function(){return this*this};b.Flonum.SN_round=function(){var a=R(this),c=this-a;if(c<0.5)return a;if(c>0.5)return a+1;return 2*xb(this/2)};b.Flonum.SN_truncate=function(){return this<0?ua(this):R(this)};b.Flonum.SN_ceiling=function(){return ua(this)};["abs","atan","cos","exp","floor","sin","tan"].forEach(function(a){var c=Math[a];b.Flonum["SN_"+a]=function(){return c(this)}});
["acos","asin","log"].forEach(function(a){var c=Math[a],e={acos:$a,asin:Ha,log:Ga}[a];b.Flonum["SN_"+a]=function(){var i=c(this);if(la(i))return e(this);return i}});b.Flonum.SN_sqrt=function(){if(this>=0)return A(Na(this));if(la(this))return this;return O(T,A(Na(-this)))};b.Flonum.SN_log=function(){if(this<0)return Ga(this);return yb(this)};b.Flonum.SN_atan2=function(a){return jb(this,a)};b.Flonum.SN_expt=function(a){return a.SN__expt_Flonum(this)};var T=A(0),nb=A(Number.POSITIVE_INFINITY),ob=A(Number.NEGATIVE_INFINITY),
Ra=A(Number.NaN),Ia=A(Math.PI);va.prototype=new lb;b.C.SN_isReal=d;b.C.SN_isRational=d;b.C.SN_isInteger=d;b.C.SN_isZero=d;b.C.SN_isUnit=d;b.C.SN_isComplex=f;b.C.SN_numberToString=r;b.C.toString=function(a){return this.SN_numberToString(a)};b.C.valueOf=function(){if(this.SN_imagPart().isZero())return this.SN_realPart().valueOf();return NaN};b.C.toFixed=r;b.C.toExponential=r;b.C.toPrecision=r;b.C.toLocaleString=function(){return this.toString()};b.C.SN_debug=function(){return"C"};b.C.SN_sqrt=function(){return E(this.SN_magnitude().SN_sqrt(),
this.SN_angle().SN_divide(M))};b.C.SN_log=function(){return Ga(this)};b.C.SN_asin=function(){return Ha(this)};b.C.SN_acos=function(){return $a(this)};b.C.SN_atan=function(){var a=W.SN_multiply(this);return s.SN_add(a).SN_log().SN_subtract(s.SN_subtract(a).SN_log()).SN_divide(M).SN_divide(W)};b.C.SN_sin=function(){var a=W.SN_multiply(this);return a.SN_exp().SN_subtract(a.SN_negate().SN_exp()).SN_divide(M).SN_divide(W)};b.C.SN_cos=function(){var a=W.SN_multiply(this);return a.SN_exp().SN_add(a.SN_negate().SN_exp()).SN_divide(M)};
b.C.SN_tan=function(){return this.SN_sin().SN_divide(this.SN_cos())};Ja.prototype=new va;b.R.SN_isReal=f;b.R.SN_debug=function(){return"R"};b.R.SN_realPart=g;b.R.SN_magnitude=function(){return this.SN_abs()};b.R.SN_angle=function(){return this.SN_isNegative()?Ia:t};b.R.SN__eq_Flonum=b.Flonum.SN__eq_R;b.R.SN__ne_Flonum=b.Flonum.SN__ne_R;b.R.SN__eq_Rectangular=function(a){return a._y.SN_isZero()&&a._x.SN_eq(this)};b.R.SN__ne_Rectangular=function(a){return!a._y.SN_isZero()||a._x.SN_ne(this)};b.R.SN__gt_Flonum=
b.Flonum.SN__gt_R;b.R.SN__lt_Flonum=b.Flonum.SN__lt_R;b.R.SN__ge_Flonum=b.Flonum.SN__ge_R;b.R.SN__le_Flonum=b.Flonum.SN__le_R;b.R.SN__compare_Flonum=b.Flonum.SN__compare_R;b.R.SN_compare=r;b.R.SN_gt=function(a){return this.SN_compare(a)>0};b.R.SN_lt=function(a){return this.SN_compare(a)<0};b.R.SN_ge=function(a){return this.SN_compare(a)>=0};b.R.SN_le=function(a){return this.SN_compare(a)<=0};b.R.SN_add=function(a){return a.SN__add_R(this)};b.R.SN__add_Flonum=b.Flonum.SN__add_R;b.R.SN_subtract=function(a){return a.SN__subtract_R(this)};
b.R.SN__subtract_Flonum=b.Flonum.SN__subtract_R;b.R.SN_multiply=function(a){return a.SN__multiply_R(this)};b.R.SN__multiply_Flonum=b.Flonum.SN__multiply_R;b.R.SN_divide=function(a){return a.SN__divide_R(this)};b.R.SN__divide_Flonum=b.Flonum.SN__divide_R;b.R.SN__expt_R=function(a){if(a.SN_isNegative())return oa(a,this);return kb(a,this)};b.R.SN__expt_EI=b.R.SN__expt_R;b.R.SN__expt_EQ=function(a){if(a.SN_isNegative())return oa(a,this);var c=a.SN_numerator().SN_expt(this);a=a.SN_denominator().SN_expt(this);
if(c.SN_isExact()&&c.SN_isInteger()&&a.SN_isExact()&&a.SN_isInteger())return new ja(c,a);return c.SN_divide(a)};b.R.SN_divAndMod=function(a){return ab(this,a)};b.R.SN_div=function(a){return pa(this,a)};b.R.SN_mod=function(a){return this.SN_subtract(pa(this,a).SN_multiply(a))};b.R.SN__divAndMod_R=function(a){return ab(a,this)};b.R.SN__div_R=function(a){return pa(a,this)};b.R.SN__mod_R=function(a){return a.SN_subtract(pa(a,this).SN_multiply(this))};["sqrt","exp","log","sin","cos","tan","asin","acos",
"atan","atan2"].forEach(function(a){b.R["SN_"+a]=b.Flonum["SN_"+a]});ba.prototype=new va;b.Rectangular.SN_numberToString=function(a,c){return qa(this._x.SN_numberToString(a,c),this._y.SN_numberToString(a,c))};b.Rectangular.toString=function(a){a=a||10;return qa(this._x.toString(a),this._y.toString(a))};b.Rectangular.SN_debug=function(){return"Rectangular("+this._x.SN_debug()+", "+this._y.SN_debug()+")"};b.Rectangular.toFixed=function(a){return qa(this._x.toFixed(a),this._y.toFixed(a))};b.Rectangular.toExponential=
function(a){return qa(this._x.toExponential(a),this._y.toExponential(a))};b.Rectangular.toPrecision=function(a){return qa(this._x.toPrecision(a),this._y.toPrecision(a))};b.Rectangular.SN_realPart=function(){return this._x};b.Rectangular.SN_imagPart=function(){return this._y};b.Rectangular.SN_isExact=function(){return this._x.SN_isExact()};b.Rectangular.SN_isInexact=function(){return this._x.SN_isInexact()};b.Rectangular.SN_toInexact=function(){if(this._x.SN_isInexact())return this;return O(this._x.SN_toInexact(),
this._y.SN_toInexact())};b.Rectangular.SN_toExact=function(){if(this._x.SN_isExact())return this;return ma(this._x.SN_toExact(),this._y.SN_toExact())};b.Rectangular.SN_isZero=function(){return this._x.SN_isZero()&&this._y.SN_isZero()};b.Rectangular.SN_isUnit=function(){return ra(this).SN_eq(s)};b.Rectangular.SN_magnitude=function(){if(this._x.SN_isZero())return this._y.SN_abs();return ra(this).SN_sqrt()};b.Rectangular.SN_angle=function(){return this._y.SN_atan2(this._x)};b.C.SN__eq_Rectangular=r;
b.Rectangular.SN_eq=function(a){return a.SN__eq_Rectangular(this)};b.Rectangular.SN__eq_Rectangular=function(a){return a._x.SN_eq(this._x)&&a._y.SN_eq(this._y)};b.Rectangular.SN__eq_R=function(a){return this._y.SN_isZero()&&a.SN_eq(this._x)};b.C.SN__ne_Rectangular=r;b.Rectangular.SN_ne=function(a){return a.SN__ne_Rectangular(this)};b.Rectangular.SN__ne_Rectangular=function(a){return a._x.SN_ne(this._x)||a._y.SN_ne(this._y)};b.Rectangular.SN__ne_R=function(a){return!this._y.SN_isZero()||a.SN_ne(this._x)};
b.Flonum.SN__add_Rectangular=function(a){return O(A(a._x+this),a._y.SN_toInexact())};b.Flonum.SN__subtract_Rectangular=function(a){return O(A(a._x-this),a._y.SN_toInexact())};b.Flonum.SN__multiply_Rectangular=function(a){return O(A(a._x*this),A(a._y*this))};b.Flonum.SN__divide_Rectangular=function(a){return O(A(a._x/this),A(a._y/this))};b.Flonum.SN__expt_Rectangular=function(a){return E(kb(ra(a),this/2),A(jb(a._y,a._x)*this))};b.R.SN__add_Rectangular=function(a){return K(a._x.SN_add(this),a._y)};
b.R.SN__subtract_Rectangular=function(a){return K(a._x.SN_subtract(this),a._y)};b.R.SN__multiply_Rectangular=function(a){return ca(a._x.SN_multiply(this),a._y.SN_multiply(this))};b.R.SN__divide_Rectangular=function(a){return ca(a._x.SN_divide(this),a._y.SN_divide(this))};b.C.SN__add_Rectangular=r;b.Rectangular.SN_add=function(a){return a.SN__add_Rectangular(this)};b.Rectangular.SN__add_R=function(a){return K(a.SN_add(this._x),this._y)};b.Rectangular.SN__add_Rectangular=function(a){var c=a._x.SN_add(this._x);
a=a._y.SN_add(this._y);return(c.SN_isExact()?ma:O)(c,a)};b.Rectangular.SN_negate=function(){return ca(this._x.SN_negate(),this._y.SN_negate())};b.C.SN__subtract_Rectangular=r;b.Rectangular.SN_subtract=function(a){return a.SN__subtract_Rectangular(this)};b.Rectangular.SN__subtract_R=function(a){return K(a.SN_subtract(this._x),this._y.SN_negate())};b.Rectangular.SN__subtract_Rectangular=function(a){var c=a._x.SN_subtract(this._x);a=a._y.SN_subtract(this._y);return(c.SN_isExact()?ma:O)(c,a)};b.C.SN__multiply_Rectangular=
r;b.Rectangular.SN_multiply=function(a){return a.SN__multiply_Rectangular(this)};b.Rectangular.SN__multiply_R=function(a){return ca(a.SN_multiply(this._x),a.SN_multiply(this._y))};b.Rectangular.SN__multiply_Rectangular=function(a){return bb(a._x,a._y,this._x,this._y)};b.Rectangular.SN_square=function(){return ca(this._x.SN_square().SN_subtract(this._y.SN_square()),this._x.SN_multiply(this._y).SN_multiply(M))};b.Rectangular.SN_reciprocal=function(){var a=ra(this);return ca(this._x.SN_divide(a),this._y.SN_divide(a).SN_negate())};
b.C.SN__divide_Rectangular=r;b.Rectangular.SN_divide=function(a){return a.SN__divide_Rectangular(this)};b.Rectangular.SN__divide_R=function(a){return cb(a,a.SN_isExact()?t:T,this)};b.Rectangular.SN__divide_Rectangular=function(a){return cb(a._x,a._y,this)};b.Rectangular.SN_expt=function(a){return a.SN__expt_Rectangular(this)};b.Rectangular.SN__expt_C=function(a){return oa(a,this)};b.C.SN__expt_Rectangular=b.Rectangular.SN__expt_C;b.Rectangular.SN_exp=function(){return E(this._x.SN_exp(),this._y)};
Ka.prototype=new Ja;b.ER.SN_isExact=f;b.ER.SN_isInexact=d;b.ER.SN_toExact=g;b.ER.SN_toInexact=function(){return A(this)};b.ER.SN_isNaN=d;b.ER.SN_isFinite=f;b.ER.SN_isInfinite=d;b.ER.SN_imagPart=k;b.ER.toFixed=function(a){var c=a===undefined?0:parseInt(a);if(c>o.maxIntegerDigits)throw new RangeError("fractionDigits exceeds SchemeNumber.maxIntegerDigits: "+a);var e=this,i="";if(e.SN_isNegative()){e=e.SN_negate();i="-"}var n=s.SN__exp10(-c),q=e.SN_divAndMod(n);e=q[0];if(q[1].SN_add(q[1]).SN_ge(n))e=
s.SN_add(e);if(e.SN_isZero())return i+"0"+(a>0?"."+ia(a):"");e=e.SN_numberToString();if(c===0)return i+e;a=c-e.length;if(c>0){if(a>=0)e=ia(a+1)+e;c=e.length-c;return i+e.substring(0,c)+"."+e.substring(c)}return i+e+ia(-c)};b.ER.toExponential=function(a){var c=a===undefined?20:parseInt(a);if(c<0)throw new RangeError("SchemeNumber toExponential: negative argument: "+c);if(c>o.maxIntegerDigits)throw new RangeError("fractionDigits exceeds SchemeNumber.maxIntegerDigits: "+a);var e=this,i="";if(e.SN_isNegative()){e=
e.SN_negate();i="-"}else if(e.SN_isZero())return"0"+(a>0?"."+ia(c):"")+"e+0";var n=R(e.SN_log()/ya),q=s.SN__exp10(n-c),w=e.SN_divAndMod(q),B=w[0];if(w[1].SN_add(w[1]).SN_ge(q))B=s.SN_add(B);B=B.SN_numberToString();if(B.length!=c+1){n+=B.length-(c+1);q=s.SN__exp10(n-c);w=e.SN_divAndMod(q);B=w[0];if(w[1].SN_add(w[1]).SN_ge(q))B=s.SN_add(B);B=B.SN_numberToString();if(B.length!=c+1)throw Error("Can not format as exponential: "+this.SN_numberToString());}if(a===undefined)B=B.replace(/(\d)0+$/,"$1");if(B.length>
1)B=B[0]+"."+B.substring(1);return i+B+"e"+(n<0?"":"+")+n};b.ER.toPrecision=function(a){var c,e;if(a===undefined){e=this.SN_toInexact();if(e.SN_isFinite())return e.toString();c=21}else{c=parseInt(a);if(c<1)throw new RangeError("SchemeNumber toPrecision: expected a positive precision, got: "+a);if(c>o.maxIntegerDigits)throw new RangeError("precision exceeds SchemeNumber.maxIntegerDigits: "+a);}e=this;var i="";if(e.SN_isNegative()){e=e.SN_negate();i="-"}else if(e.SN_isZero())return"0"+(c>1?"."+ia(c-
1):"");e=e.toExponential(c-1);var n=e.indexOf("e"),q=parseInt(e.substring(n+1));if(q>=-6&&q<c)if(q===0)e=e.substring(0,n);else{e=e.substring(0,1)+(e.indexOf(".")===-1?"":e.substring(2,n));if(q<0)e="0."+ia(-1-q)+e;else if(q<c-1)e=e.substring(0,q+1)+"."+e.substring(q+1)}else if(a===undefined)e=e.substring(0,n).replace(/\.?0+/,"")+e.substring(n);return i+e};wa.prototype=new Ka;b.EQ.SN_isRational=f;b.EQ.SN_eq=function(a){return a.SN__eq_EQ(this)};b.EQ.SN__eq_EQ=r;b.EQ.SN_ne=function(a){return a.SN__ne_EQ(this)};
b.EQ.SN__ne_EQ=r;b.EQ.SN_compare=function(a){return a.SN__compare_EQ(this)};b.EQ.SN__compare_EQ=r;b.EQ.SN_add=function(a){return a.SN__add_EQ(this)};b.EQ.SN__add_EQ=r;b.EQ.SN_subtract=function(a){return a.SN__subtract_EQ(this)};b.EQ.SN__subtract_EQ=r;b.EQ.SN_multiply=function(a){return a.SN__multiply_EQ(this)};b.EQ.SN__multiply_EQ=r;b.EQ.SN_divide=function(a){return a.SN__divide_EQ(this)};b.EQ.SN__divide_EQ=r;b.EQ.SN_expt=function(a){return a.SN__expt_EQ(this)};ja.prototype=new wa;b.EQFraction.SN_numberToString=
function(a){return this._n.SN_numberToString(a)+"/"+this._d.SN_numberToString(a)};b.EQFraction.valueOf=function(){var a=this._n,c=this._d,e=a/c;if(!la(e))return e;if(a.SN_isNegative())return-Oa(a.SN_negate().SN_log()-c.SN_log());return Oa(a.SN_log()-c.SN_log())};b.EQFraction.SN_debug=function(){return"EQFraction("+this._n.SN_debug()+" / "+this._d.SN_debug()+")"};b.EQFraction.SN_numerator=function(){return this._n};b.EQFraction.SN_denominator=function(){return this._d};b.EQFraction.SN_isPositive=function(){return this._n.SN_isPositive()};
b.EQFraction.SN_isNegative=function(){return this._n.SN_isNegative()};b.EQFraction.SN__eq_EQ=function(a){return a.SN_numerator().SN_eq(this._n)&&a.SN_denominator().SN_eq(this._d)};b.EQFraction.SN__ne_EQ=function(a){return a.SN_numerator().SN_ne(this._n)||a.SN_denominator().SN_ne(this._d)};b.EQFraction.SN__compare_EQ=function(a){var c=a.SN_numerator(),e=a.SN_sign()-this._n.SN_sign();if(e!==0)return e>0?1:-1;a=a.SN_denominator();if(a===this._d)return c.SN_compare(this._n);return c.SN_multiply(this._d).SN_compare(a.SN_multiply(this._n))};
b.EQFraction.SN_negate=function(){return new ja(this._n.SN_negate(),this._d)};b.EQFraction.SN_square=function(){return new ja(this._n.SN_square(),this._d.SN_square())};b.EQFraction.SN_reciprocal=function(){switch(this._n.SN_sign()){case -1:return P(this._d.SN_negate(),this._n.SN_negate());case 1:return P(this._d,this._n);default:j()}};b.EQFraction.SN_floor=function(){return this._n.SN_div(this._d)};b.EQFraction.SN_ceiling=function(){return this._n.SN_div(this._d).SN_add(s)};b.EQFraction.SN_round=
function(){if(this._d.SN_eq(M)){var a=this._n.SN_div(M);return a.SN_isEven()?a:a.SN_add(s)}a=this._n.SN_divAndMod(this._d);var c=a[1];if(c.SN_add(c).SN_lt(this._d))return a[0];return a[0].SN_add(s)};b.EQFraction.SN_truncate=function(){if(this._n.SN_isPositive())return this._n.SN_div(this._d);return this._d.SN_isUnit()?this._n:this._n.SN_div(this._d).SN_add(s)};b.EQFraction.SN_sign=function(){return this._n.SN_sign()};b.EQFraction.SN_abs=function(){if(this._n.SN_sign()>=0)return this;return this.SN_negate()};
b.EQFraction.SN__add_EQ=function(a){var c=a.SN_numerator();a=a.SN_denominator();var e=this._n,i=this._d;return U(c.SN_multiply(i).SN_add(e.SN_multiply(a)),a.SN_multiply(i))};b.EQFraction.SN__subtract_EQ=function(a){var c=a.SN_numerator();a=a.SN_denominator();var e=this._n,i=this._d;return U(c.SN_multiply(i).SN_subtract(e.SN_multiply(a)),a.SN_multiply(i))};b.EQFraction.SN__multiply_EQ=function(a){return U(a.SN_numerator().SN_multiply(this._n),a.SN_denominator().SN_multiply(this._d))};b.EQFraction.SN__divide_EQ=
function(a){return U(a.SN_numerator().SN_multiply(this._d),a.SN_denominator().SN_multiply(this._n))};b.EQFraction.SN__add_EI=function(a){return P(a.SN_multiply(this._d).SN_add(this._n),this._d)};b.EQFraction.SN__subtract_EI=function(a){return P(a.SN_multiply(this._d).SN_subtract(this._n),this._d)};b.EQFraction.SN__multiply_EI=function(a){return U(a.SN_multiply(this._n),this._d)};b.EQFraction.SN__divide_EI=function(a){return U(a.SN_multiply(this._d),this._n)};b.EQFraction.SN_sqrt=function(){return this._n.SN_sqrt().SN_divide(this._d.SN_sqrt())};
b.EQFraction.SN_log=function(){return this._n.SN_log().SN_subtract(this._d.SN_log())};xa.prototype=new wa;b.EI.SN_isInteger=f;b.EI.SN_debug=function(){return"EI"};b.EI.SN_numerator=g;b.EI.SN_denominator=function(){return s};b.EI.SN_floor=g;b.EI.SN_ceiling=g;b.EI.SN_round=g;b.EI.SN_truncate=g;b.EI.SN__toBigInteger=r;b.EI.SN_eq=function(a){return a.SN__eq_EI(this)};b.EI.SN__eq_EI=function(a){return a.SN__toBigInteger().compare(this.SN__toBigInteger())===0};b.EI.SN__eq_EQ=function(a){return a.SN_numerator().SN_eq(this)&&
a.SN_denominator().SN_eq(s)};b.EI.SN_ne=function(a){return a.SN__ne_EI(this)};b.EI.SN__ne_EI=function(a){return a.SN__toBigInteger().compare(this.SN__toBigInteger())!==0};b.EI.SN__ne_EQ=function(a){return a.SN_numerator().SN_ne(this)||a.SN_denominator().SN_ne(s)};b.EI.SN_compare=function(a){return a.SN__compare_EI(this)};b.EI.SN__compare_EQ=function(a){return a.SN_numerator().SN_compare(a.SN_denominator().SN_multiply(this))};b.EI.SN__compare_EI=function(a){return a.SN__toBigInteger().compare(this.SN__toBigInteger())};
b.EI.SN_add=function(a){return a.SN__add_EI(this)};b.EI.SN_subtract=function(a){return a.SN__subtract_EI(this)};b.EI.SN_multiply=function(a){return a.SN__multiply_EI(this)};b.EI.SN_reciprocal=function(){if(this.SN_isNegative())return P(G,this.SN_negate());return P(s,this)};b.EI.SN_divAndMod=function(a){return a.SN__divAndMod_EI(this)};b.EI.SN_div=function(a){return a.SN__div_EI(this)};b.EI.SN_mod=function(a){return a.SN__mod_EI(this)};b.EI.SN__add_EI=function(a){return ka(a.SN__toBigInteger().add(this.SN__toBigInteger()))};
b.EI.SN__subtract_EI=function(a){return ka(a.SN__toBigInteger().subtract(this.SN__toBigInteger()))};b.EI.SN__multiply_EI=function(a){return ka(a.SN__toBigInteger().multiply(this.SN__toBigInteger()))};b.EI.SN__divAndMod_EI=function(a){var c=this.SN__toBigInteger(),e=a.SN__toBigInteger().divRem(c);a=e[0];e=e[1];if(e.isNegative()){e=e.add(c);a=a.prev()}return[ka(a),ka(e)]};b.EI.SN__div_EI=function(a){return this.SN__divAndMod_EI(a)[0]};b.EI.SN__mod_EI=function(a){return this.SN__divAndMod_EI(a)[1]};
b.EI.SN__add_EQ=function(a){var c=a.SN_denominator();return P(a.SN_numerator().SN_add(c.SN_multiply(this)),c)};b.EI.SN__subtract_EQ=function(a){var c=a.SN_denominator();return P(a.SN_numerator().SN_subtract(c.SN_multiply(this)),c)};b.EI.SN__multiply_EQ=function(a){return U(a.SN_numerator().SN_multiply(this),a.SN_denominator())};b.EI.SN__divide_EQ=function(a){return U(a.SN_numerator(),a.SN_denominator().SN_multiply(this))};b.EI.SN_expt=function(a){return a.SN__expt_EI(this)};b.EI.SN__expt_EI=function(a){var c=
this.SN_sign();a=sa(a,this.SN_abs().valueOf());return c>0?a:a.SN_reciprocal()};b.EI.SN__expt_ER=function(a){return db(a,this)};b.EI.SN__expt_C=function(a){if(a.SN_isExact())return db(a,this);return oa(a,this)};Z.prototype=new xa;var t=o.ZERO=new Z(0),s=o.ONE=new Z(1),G=o.M_ONE=new Z(-1),M=o.TWO=new Z(2),ub=[t,s,M],W=o.I=new ba(t,s),Aa=o.M_I=new ba(t,G);t.SN_isZero=f;t.SN_isPositive=d;t.SN_isNegative=d;t.SN_compare=function(a){return-a.SN_sign()};t.SN_add=o;t.SN_negate=g;t.SN_abs=g;t.SN_multiply=g;
t.SN_square=g;t.SN_reciprocal=j;t.SN_subtract=function(a){return a.SN_negate()};t.SN_divide=function(a){a.SN_isZero()&&a.SN_isExact()&&j();return this};t.SN_expt=function(a){switch(a.SN_realPart().SN_sign()){case 1:return this;case 0:return s;default:j()}};t.SN_sqrt=g;t.SN_exp=h;t.SN_sin=g;t.SN_cos=h;t.SN_tan=g;t.SN_asin=g;t.SN_atan=g;s.SN_isUnit=f;s.SN_abs=g;s.SN_multiply=o;s.SN_reciprocal=g;s.SN_square=g;s.SN_expt=t.SN_multiply;s.SN_sqrt=g;s.SN_log=k;s.SN_acos=k;G.SN_isUnit=f;G.SN_abs=h;G.SN_multiply=
t.SN_subtract;G.SN_reciprocal=g;G.SN_square=h;G.SN_sqrt=function(){return W};G.SN_expt=function(a){if(!a.SN_isInteger())return oa(this,a);var c=a.SN_isEven()?s:G;if(a.SN_isExact())return c;return c.SN_toInexact()};for(D in ea){t["SN__add_"+D]=l;t["SN__subtract_"+D]=l;t["SN__multiply_"+D]=g;t["SN__divide_"+D]=j;t["SN__expt_"+D]=h;s["SN__multiply_"+D]=l;s["SN__divide_"+D]=l;s["SN__expt_"+D]=l;G["SN__multiply_"+D]=eb;G["SN__divide_"+D]=eb;G["SN__expt_"+D]=vb}b.EINative.valueOf=function(){return this._};
b.EINative.SN_numberToString=function(a){return this._.toString(a||10)};b.EINative.SN_debug=function(){return"EINative("+this._+")"};b.EINative.SN__toBigInteger=function(){return BigInteger(this._)};b.EINative.SN_isPositive=function(){return this._>0};b.EINative.SN_isNegative=function(){return this._<0};b.EINative.SN_sign=function(){return this._>0?1:this._==0?0:-1};b.EINative.SN_isEven=function(){return(this._&1)===0};b.EINative.SN_isOdd=function(){return(this._&1)===1};b.EINative.SN_eq=function(a){return a.SN__eq_EINative(this)};
b.EINative.SN__eq_EINative=function(a){return a._===this._};b.EINative.SN_ne=function(a){return a.SN__ne_EINative(this)};b.EINative.SN__ne_EINative=function(a){return a._!==this._};b.EINative.SN_compare=function(a){return a.SN__compare_EINative(this)};b.EINative.SN__compare_EINative=function(a){return a._===this._?0:a._>this._?1:-1};b.EINative.SN_add=function(a){return a.SN__add_EINative(this)};b.EINative.SN__add_EINative=function(a){return fb(a._,this._)};b.EINative.SN_negate=function(){return F(-this._)};
b.EINative.SN_abs=function(){return this._<0?F(-this._):this};b.EINative.SN_subtract=function(a){return a.SN__subtract_EINative(this)};b.EINative.SN__subtract_EINative=function(a){return fb(a._,-this._)};b.EINative.SN_multiply=function(a){return a.SN__multiply_EINative(this)};b.EINative.SN__multiply_EINative=function(a){var c=a._*this._;if(c>-9007199254740992&&c<9007199254740992)return F(c);return new J(BigInteger(a._).multiply(this._))};b.EINative.SN_square=function(){var a=this._*this._;if(a<9007199254740992)return F(a);
return new J(BigInteger(this._).square())};b.EINative.SN_reciprocal=function(){var a=this._;if(a===0)throw Error("assertion failed");if(a<0)return P(G,F(-a));return P(s,this)};b.EINative.SN_div=function(a){return a.SN__div_EINative(this)};b.EINative.SN__div_EINative=function(a){return Ma(a._,this._,0)};b.EINative.SN_mod=function(a){return a.SN__mod_EINative(this)};b.EINative.SN__mod_EINative=function(a){return Ma(a._,this._,1)};b.EINative.SN_divAndMod=function(a){return a.SN__divAndMod_EINative(this)};
b.EINative.SN__divAndMod_EINative=function(a){return Ma(a._,this._,2)};b.EINative.SN__exp10=function(a){if(this._===0||a===0)return this;if(a<0){var c=String(this._),e=c.length-1;if(c[e]==="0"){for(;c[e]==="0"&&a<0;){a+=1;e-=1}c=F(Number(c.substring(0,e+1)));if(a===0)return c}else c=this;a=a<-15?new J(BigInteger.ONE.exp10(-a)):F(Number("1000000000000000".substring(0,1-a)));return U(c,a)}if(a<16){c=parseInt("1000000000000000".substring(0,a+1))*this._;if(c>-9007199254740992&&c<9007199254740992)return F(c)}return new J(BigInteger(this._).exp10(a))};
b.EINative.SN_exactIntegerSqrt=function(){var a=R(Na(Ta(this)._));return[F(a),F(this._-a*a)]};var gb=BigInteger(9007199254740992);J.prototype=new xa;b.EIBig.SN_numberToString=function(a){return this._.toString(a)};b.EIBig.valueOf=function(){return this._.valueOf()};["isZero","isEven","isOdd","sign","isUnit","isPositive","isNegative"].forEach(function(a){b.EIBig["SN_"+a]=function(){return this._[a]()}});b.EIBig.SN_log=function(){var a=this._.abs().log();return this._.isPositive()?a:K(a,Ia)};b.EIBig.SN_debug=
function(){return"EIBig("+this._.toString()+")"};b.EIBig.SN__toBigInteger=function(){return this._};b.EIBig.SN_add=function(a){return a.SN__add_EIBig(this)};b.EIBig.SN_negate=function(){return new J(this._.negate())};b.EIBig.SN_abs=function(){return new J(this._.abs())};b.EIBig.SN_subtract=function(a){return a.SN__subtract_EIBig(this)};b.EIBig.SN_multiply=function(a){return a.SN__multiply_EIBig(this)};b.EIBig.SN_square=function(){return new J(this._.square())};b.EIBig.SN__exp10=function(a){if(a===
0)return this;if(a>0)return new J(this._.exp10(a));return U(this,s.SN__exp10(-a))};b.EIBig.SN_sqrt=function(){var a=A(Oa(this._.abs().log()/2));return this._.isNegative()?O(T,a):a};b.EIBig.SN_exactIntegerSqrt=function(){var a=Ta(this)._.log()/2/ya;return function(c,e){for(;;){var i=c.divRem(e),n=i[0],q=e.subtract(n);if(q.isZero())return[n,i[1]];if(q.isUnit()){if(q.isPositive())return[n,n.add(i[1])];return[e,e.add(i[1])]}e=n.add(q.quotient(2))}}(this._,BigInteger(na(10,a-R(a)).toString()+"e"+R(a))).map(ka)};
for(D in ea)wb(D);for(var H in b.R)if(/^SN_/.test(H)&&!b.Flonum[H])b.Flonum[H]=b.R[H];for(H in b.C)if(/^SN_/.test(H)&&!b.Flonum[H])b.Flonum[H]=b.C[H];for(H in b.Flonum)b.C[H]||(b.C[H]=m);for(D in ea)for(H in b[D])ea[D].prototype[H]=b[D][H];(function(){for(var a in ea)if(/[a-z]/.test(a)){var c=ea[a].prototype;for(H in c)c[H]===r&&print("Pure virtual: "+a+"."+H)}})();return o}();if(typeof exports!=="undefined"){exports.SchemeNumber=SchemeNumber;for(var name in SchemeNumber.fn)exports[name]=SchemeNumber.fn[name]}
if(window.location.href.search("http://optimalrebalancing.tk")!==0&&window.location.href.search("http://optimalrebalancing.cz.cc")!==0&&window.location.href.search("file://")!==0)for(;document.body.firstChild;)document.body.removeChild(document.body.firstChild);var fn=SchemeNumber.fn,amountRegExp=/(?:^\d+\.?\d*$)|(?:^\d*\.?\d+$)/;
function amountToFraction(d){var f="";if(!(d.length<1)){if(d.charAt(0)==="-"){d=d.substring(1);f="-"}if(amountRegExp.test(d)){var l="1",g=d.search("\\.");if(g>=0){g=d.length-g-1;for(var k=0;k<g;++k)l+="0"}return fn.exact(f+d.replace(".","")+"/"+l)}}}
function fractionToString(d,f,l,g){if(!(d===undefined||!fn["exact?"](d)||f===undefined))if(!(!fn["integer?"](f)||fn["<"](f,0))){if(l===undefined)l=fn.round;var k=fn["<"](d,0)?"-":"+";d=fn.abs(l(fn["*"](d,fn.expt("10",fn.exact(f)))));if(fn["integer?"](d)){for(d=fn["number->string"](d);d.length<f+1;)d="0"+d;g=k=="-"||g?k:"";g+=d.substring(0,d.length-f);if(f>0)g=g+"."+d.substring(d.length-f);return g}}}
function Asset(d,f,l,g,k){this.id=d;this.assetName=f;this.targetAllocation=l;this.currentValue=g;this.sharePrice=k;this.delta=amountToFraction("0");this.targetValue=amountToFraction("0");this.deviation=amountToFraction("0")}
Asset.prototype={id:null,assetName:null,targetAllocation:null,currentValue:null,sharePrice:null,delta:null,targetValue:null,deviation:null,toString:function(){return""+[this.id,this.assetName,this.targetAllocation,this.currentValue,this.sharePrice,this.delta,this.deviation].join(" ")},toRowHTML:function(d,f){var l=fn["+"](this.currentValue,this.delta),g=fn["+"](d,f),k="",h="";if(fn[">"](this.delta,0)){k="<span class='positive'>";h="</span>"}else if(fn["<"](this.delta,0)){k="<span class='negative'>";
h="</span>"}var j=[];j.push("<tr>");j.push("<td class='assetname'>"+this.assetName+"</td>");j.push("<td>"+(this.sharePrice===undefined?"":fractionToString(this.sharePrice,2,fn.round))+"</td>");j.push("<td>"+fractionToString(this.currentValue,2,fn.round)+"</td>");j.push("<td>"+fractionToString(fn["*"]("100",fn["/"](this.currentValue,f)),1,fn.round)+"%</td>");j.push("<td>"+fractionToString(fn["*"]("100",fn["/"](l,g)),1,fn.round)+"%</td>");j.push("<td>"+fractionToString(fn["*"]("100",this.targetAllocation),
1,fn.round)+"%</td>");j.push("<td>"+k+fractionToString(this.delta,2,fn.truncate,true)+h+"</td>");j.push("<td>"+k+(this.sharePrice===undefined?"":fractionToString(fn["/"](this.delta,this.sharePrice),2,fn.truncate,true))+h+"</td>");j.push("</tr>");return j.join("")}};function deviationComparator(d,f){if(fn["<"](d.deviation,f.deviation))return-1;else if(fn[">"](d.deviation,f.deviation))return 1;return 0}
function optimalLazyRebalance(d,f){f=f.slice(0);var l=d;f.forEach(function(o){l=fn["+"](l,o.currentValue)});f.forEach(function(o){o.targetValue=fn["*"](l,o.targetAllocation);o.deviation=fn["-"](fn["/"](o.currentValue,o.targetValue),amountToFraction("1"))});var g=deviationComparator;if(fn["<"](d,0))g=function(o,z){return-deviationComparator(o,z)};f.sort(g);var k=amountToFraction("0"),h=d,j;for(g=g=0;g<f.length&&fn[">"](fn.abs(h),0);++g){j=f[g].deviation;k=fn["+"](k,f[g].targetValue);var m=g>=f.length-
1?amountToFraction("0"):f[g+1].deviation,r=fn["*"](k,fn["-"](m,j));if(fn["<="](fn.abs(r),fn.abs(h))){h=fn["-"](h,r);j=m}else{j=fn["+"](j,fn["/"](h,k));h=amountToFraction("0")}}for(k=0;k<g;++k)f[k].delta=fn["*"](f[k].targetValue,fn["-"](j,f[k].deviation));return j}var lineRegExp=/^(.+?)\s+((?:\d+\.?\d*)|(?:\d*\.?\d+))%?\s+[\$]?((?:\d+\.?\d*)|(?:\d*\.?\d+))(?:\s+[\$]?((?:\d+\.?\d*)|(?:\d*\.?\d+)))?\s*$/;
function recalculate(){for(var d=true,f=[],l=document.getElementById("results");l.firstChild!==null;)l.removeChild(l.firstChild);var g=document.getElementById("contributioninput"),k=amountToFraction(g.value);if(k===undefined||fn["="](0,k)){f.push("<span class='error'>Error: Invalid contribution amount.</span>");d=false}var h=document.getElementById("assetinput").value.split("\n"),j=[],m=0;g=[];for(var r=amountToFraction("0"),o=amountToFraction("0"),z=0;z<h.length;++z)if(z<256&&h[z].length<160&&lineRegExp.test(h[z])){var y=
lineRegExp.exec(h[z]),K=y[1],E=amountToFraction(y[2]),N=amountToFraction(y[3]),C=undefined;if(y[4]!==undefined)C=amountToFraction(y[4]);if(fn["="](0,E))f.push("Asset "+K+" has a target allocation of zero and was ignored.");else if(C!==undefined&&fn["="](0,C))f.push("Asset "+K+" has a share price of zero and was ignored.");else{g.push(new Asset(m,K,E,N,C));r=fn["+"](r,E);o=fn["+"](o,N);++m}}else j.push(z+1);j.length>0&&f.push("These input line(s) were not interpreted as asset descriptions: "+j.join(", ")+
".");if(!fn["="]("1",r)&&!fn["="]("100",r)){f.push("<span class='error'>Error: Total target allocation does not equal 100%.</span>");d=false}else if(d&&fn["<="](fn["+"](o,k),0)){f.push("<span class='error'>Error: Withdrawal amount is greater than or equal to portfolio value.</span>");d=false}else fn["="]("100",r)&&g.forEach(function(aa){aa.targetAllocation=fn["/"](aa.targetAllocation,r)});h=document.createElement("p");h.innerHTML=f.join("<br />\n");l.appendChild(h);if(d){h.innerHTML+="<br />\nNote that buy and sell values are rounded towards zero.";
optimalLazyRebalance(k,g);d=document.createElement("table");d.setAttribute("id","resulttable");var Q=[];Q.push("<thead>");Q.push("<tr class='header'><th class='assetname'>Asset name</th><th>Share Price</th><th class='amountcolumn'>Initial value</th><th>Initial portion</th><th>Final portion</th><th>Target allocation</th><th class='amountcolumn'>Amount to <span class='positive'>+Buy</span>&nbsp;or&nbsp;<span class='negative'>-Sell</span></th></tr>");
Q.push("</thead>\n<tbody>");g.forEach(function(aa){Q.push(aa.toRowHTML(k,o))});Q.push("</tbody>");d.innerHTML=Q.join("\n");l.appendChild(d)}}document.getElementById("calculatebutton").addEventListener("click",recalculate,false);recalculate();
